#pragma once

#include <stdint.h>
#include <stddef.h>

enum uint8_t {
    SCREEN_COLOR_BLACK,
    SCREEN_COLOR_BLUE,
    SCREEN_COLOR_GREEN,
    SCREEN_COLOR_CYAN,
    SCREEN_COLOR_RED,
    SCREEN_COLOR_MAGENTA,
    SCREEN_COLOR_BROWN,
    SCREEN_COLOR_LIGHT_GRAY,
    SCREEN_COLOR_DARK_GRAY,
    SCREEN_COLOR_LIGHT_BLUE,
    SCREEN_COLOR_LIGHT_GREEN,
    SCREEN_COLOR_LIGHT_CYAN,
    SCREEN_COLOR_LIGHT_RED,
    SCREEN_COLOR_PINK,
    SCREEN_COLOR_YELLOW,
    SCREEN_COLOR_WHITE
};

extern void screen_init();
